import pkg from '@slack/bolt';
const { App } = pkg; //Used to create and manage Slack bots
import { WebClient } from '@slack/web-api'; //Used to send messages to Slack
import { ChatOpenAI } from '@langchain/openai';
import { ChatPromptTemplate } from '@langchain/core/prompts'; //Used to create prompts with placeholders
import express from 'express'; //Creates a backend server
import dotenv from 'dotenv';
import axios from 'axios';//Makes HTTP requests
import { initDatabase, saveMemberAnalysis, markAsSentToSlack, closeDatabase } from './db.js'

dotenv.config();

const log = {
    info: (msg, ...args) => console.log(`[INFO] ${msg}`, ...args),
    error: (msg, ...args) => console.log(`[ERROR] ${msg}`, ...args),
    debug: (msg, ...args) => process.env.NODE_ENV === "development"
        && console.log(`[DEBUG] ${msg}`, ...args)
}
//new slackAgent->Constructor runs->Create Express Server->Create Slack Bot->Create GPT-4 Connection->Setup Slack Events->Setup Backend Server->Ready to work
class SlackAIAgent {
    constructor() {
        this.app = express() //Website/Backend starts here
        this.slack = new App({ 
            token: process.env.SLACK_BOT_TOKEN,
            signingSecret: process.env.SLACK_SIGNING_SECRET,
            socketMode: true,
            appToken: process.env.SLACK_APP_TOKEN
        });
        this.webClient = new WebClient(process.env.SLACK_BOT_TOKEN);//created a connection to Slack using your bot token.Used to send messages to Slack.

        this.openai = new ChatOpenAI({
            model: "gpt-4o-mini",
            temperature: 0.3, //low value-more consistent answers,high value-more creative answer
            apiKey: process.env.OPENAI_API_KEY
        });

        this.setupSlackEvents();
        this.setupExpress();
    }

    //below code tells the bot:"When a new member joins Slack, run this code.
    setupSlackEvents() {
        this.slack.event('team_join', async ({ event }) => { //slack sends the user id
            try {
                log.info(`New member joined: ${event.user.real_name ||
                    event.user.name}`)
                const userInfo = await this.getUserInfo(event.user.id);
                 //gets detailed info about the user by reading userid
                await this.analyzeAndPostMember(userInfo); //this is AI part = User info->gpt analysis->generate report>post to slack channel
            } catch (error) { //if something goes wrong dont crash the bot instead print those errors
                log.error('Error processing team_join:', error.message)
            }
        });

        this.slack.event('member_joined_channel', async ({ event }) => {
            try {
                if (event.channeltype === 'C') {
                    log.info(`Member ${event.user} joined channel ${event.channel}`)
                    const userInfo = await this.getUserInfo(event.user);
                    await this.analyzeAndPostMember(userInfo)
                }

            }
            catch (error) {
                log.error('error processing member_joined_channel: ', error.message)
            }
            this.slack.error(async (error) => log.error('Slack error:', error.message)) //means:"If Slack encounters an error,run this function."
        });
    }


    //This function is setting up the backend server routes.
    //flow= server starts->/health->check server status->/test/analyze member->send member info->analyze with gpt->get report
    setupExpress() {
        this.app.use(express.json()); //Accept JSON data from requests

        this.app.get('/health', (req, res) => { //Check if server is running
            res.json({ status: 'healthy', timestamp: new Date().toISOString() });
        })

        if (process.env.NODE_ENV === 'development') {
            this.app.post('/test/analyze-member', async (req, res) => {
                try {
                    const { memberInfo } = req.body;
                    if (!memberInfo) return res.status(400).json({ error: 'memberInfo is required' }) //if member info is missing then return error 400
                    const analysis = await this.analyzeAndPostMember(memberInfo); //analyzeAndPostMember is function where gpt is being called and analysis is done
                    res.json({ success: true, analysis, timestamp: new Date().toISOString() }); //sends back the response generated by the function analyzeandpostmember
                } catch (error) {
                    log.error('Test analysis error:', error.message)
                    res.status(500).json({ error: 'Analysis failed', message: error.message })
                }
            });
            
        }
if (process.env.NODE_ENV === 'development') {

    this.app.post('/test/analyze-member', async (req, res) => {
        try {
            const { memberInfo } = req.body;

            if (!memberInfo) {
                return res.status(400).json({
                    error: 'memberInfo is required'
                });
            }

            const analysis = await this.analyzeAndPostMember(memberInfo);

            res.json({
                success: true,
                analysis,
                timestamp: new Date().toISOString()
            });

        } catch (error) {
            log.error('Test analysis error:', error.message);

            res.status(500).json({
                error: 'Analysis failed',
                message: error.message
            });
        }
    });

   
}
        this.app.use((err, req, res, next) => {
            log.error('Express error', err.message)
            res.status(500).json({ error: 'Internal server error' })
        })
    }


    //in this function we are fetching the data from slack but we get a lot of data some of which might be not important to us so we filter only the imp data usefull to us
    async getUserInfo(userId) {
        const result = await this.webClient.users.info({ user: userId });//fetches the data from slack
        const user = result.user;

       
        return { //we create user object to filter the data for gpt to analyse
            id: user.id,
            name: user.real_name || user.name,
            username: user.name,
            email: user.profile?.email,
            title: user.profile?.title,
            timezone: user.tz,
            profile: {
                firstName: user.profile?.first_name,
                lastName: user.profile?.last_name,
                statusText: user.profile?.status_text
            }
        };
    }

    //in this function gpt does the analysis and post it to the DB
    async analyzeAndPostMember(memberInfo) {
        let analysisId = null;
        try {
            log.info(`Processing member: ${memberInfo.name}`)
            const researchData = await this.doBasicResearch(memberInfo);  //function dobasicresearch does some research and the output is stored in researchdata
            const analysis = await this.analyzeWithAI(memberInfo, researchData);  //function analyzeWithAI uses gpt to analyse the memberinfo and research data and stores in analysis
            log.info(`Saving analysis to database for ${memberInfo.name}`);
            analysisId = await saveMemberAnalysis(memberInfo, analysis, researchData);
            await this.postAnalysisToChannel(memberInfo, analysis, researchData); //fucntion postAnalysisToChannel posts the analysis to channel

            if (analysisId) {
                await markAsSentToSlack(analysisId);
            }
        } catch (error) {
            log.error(`Error processing ${memberInfo.name}:`, error.message);
            if (analysisId) {
                log.info(`Analysis ${analysisId} saved to database but not sent to Slack due to error`);
            }
            throw error;
        }
    }



    async doBasicResearch(memberInfo) {
        const results = [];
        try {
            if (memberInfo.email && !this.isPersonalEmail(memberInfo.email)) { //we will check if the email of the new member is personal and if yes then we will split it at @
                const domain = memberInfo.email.split('@')[1];
                const companyInfo = await this.getCompanyInfo(domain); //using getCompanyInfo function we will get the info of company
                if (companyInfo) results.push(companyInfo);

                if (memberInfo.name) {
                    const githubInfo = await this.getGitHubInfo(memberInfo.name); //gives github profile of user
                    if (githubInfo) results.push(githubInfo);
                }
            }
        } catch (error) {
            log.error('Research error:', error.message);
        }
        return results;
    }

    //here we will extract the company info from the user email using the domain variable by going to the actual site of company
    //  and if this failed then we will simply set the company as domain
    async getCompanyInfo(domain) {
        try {
            const response = await axios.get(`https://www.${domain}`, //going to the actual site
                { timeout: 5000, headers: { 'User-Agent': 'Mozilla/5.0' } }); //header meaning pretends to be a user as sometimes website blocks thinking it is a bot

            const titleMatch = response.data.match(/<title>(.*?)<\/title>/i) //Find the <title> tag in the websites html,response.data contains the entire html of the website
            const title = titleMatch ? titleMatch[1] : `Company: ${domain}`;

            return {
                url: `https://www.${domain}`,
                title: title,
                content: `Company website for ${domain}`,
                type: 'company'
            }
        }
        catch (error) {
            log.error(`could not fetch ${domain}: `, error.message) //print error msg if domain couldnt be fetched
            return null;
        }
    }


    //this function will get the github profile of the user
    async getGitHubInfo(name) {
        try {
            const response = await axios.get(`https://api.github.com/search/users?q=${encodeURIComponent(name)}`,//going to the actual github
                { timeout: 5000 }
            );
            if (response.data.items && response.data.items.length > 0) { //Does items exist? AND Does it contain at least 1 user?
                const user = response.data.items[0]; //getting the first result
                return {
                    url: user.html_url,
                    title: `GitHub: ${user.login}`,
                    content: `${user.public_repos} public repositories`,
                    type: 'github'
                }
            }
        }
        catch (error) {
            log.debug('GitHub search error:', error.message)
        }
        return null;
    }


    //in this functio we will be actually analysing the member
    async analyzeWithAI(memberInfo, researchData) {
        const prompt = ChatPromptTemplate.fromTemplate(//here company is our company not the members. 
            //the lines company and product are using values from the .env file to run analysis with our own company
            `analyse this new community member for the fit of our commercial product
                 Company: ${process.env.COMPANY_NAME || 'Your Company'} 
                 Product: ${process.env.COMPANY_PRODUCT || 'Your Product'}

    Member:
    - Name: {name}
    - Email: {email}
    - Title: {title}

    Research Data:
    {research}

    Provide a JSON response with:
    - fitScore (0-100): likelihood they'd be interested in our product
    - insights: array of 3-5 key observations
    - recommendations: array of 2-4 engagement suggestions

    Consider job title, company size, technical background, and budget 
    authority.`
        );

        try {
            const researchSummary = researchData.length > 0 //if research data is avl then print the data in below format
                ? researchData.map(r => `${r.title}: ${r.content}`).join(`\\n`)
                : 'Limited research data available'
            const chain = prompt.pipe(this.openai); //creating chain between prompt and gpt using pipe,
            // because without pipe we need to fill the prompt template first and then send it to gpt 
            // but by using pipe the we can connect the prompt directly to GPT once.
            const result = await chain.invoke({ //calling gpt and providing name,email,title research to analyse
                name: memberInfo.name,   //since the prompt template is still empty we need to fill it so we will use below lines
                email: memberInfo.email || 'Not provided',
                title: memberInfo.title || 'not provided',
                research: researchSummary
            })
            const responseText = result.content || result; //saving the response from result
            const cleanedResponse =
                responseText.replace(/```json\n?|\n?```/g, '').trim() //cleans the response
            const analysis = JSON.parse(cleanedResponse) //convert string into js object 
            return {
                fitScore: Math.max(0, Math.min(100, analysis.fitScore || 50)),
                insights: Array.isArray(analysis.insights) ? analysis.insights : ['Analysis completed'], //if insights are in array then return otherwise default value-Analysis completed
                recommendations: Array.isArray(analysis.recommendations) ? analysis.recommendations : ['Follow up recommended']
            }

        }
        catch (error) {
            log.error('AI analysis error: ', error.message);
            return {
                fitScore: 50,
                insights: ['Unable to complete full analysis'],
                recommendations: ['Manual review recommended']

            }
        }
    }

    //in this function we will be now posting the analysis to the slack channel
    async postAnalysisToChannel(member, analysis, researchData) {
        const color = analysis.fitScore >= 80 ? '#36a64f'
            : analysis.fitscore >= 60 ? '#ffb84d'
                : analysis.fitscore >= 40 ? '#ff9500' : '#ff4444';
        //Slack messages are built using blocks.
        // So the below code is building the first part of the Slack report card that will be posted after GPT finishes the analysis.
        const blocks = [
            {
                type: 'header',
                text: { type: 'plain_text', text: `🔍 New Member: ${member.name}` }
            },
            {
                type: 'section',
                fields: [
                    { type: 'mrkdwn', text: `*Fit Score:* ${analysis.fitScore}/100` },
                    { type: 'mrkdwn', text: `*Email:* ${member.email || 'Not provided'}` },
                    { type: 'mrkdwn', text: `*Title:* ${member.title || 'Not provided'}` },
                ]
            }
        ];

        if (analysis.insights.length > 0) { //if insights are present then
            blocks.push({ //add one more section to slack report card
                type: 'section',
                text: {
                    type: 'mrkdwn',
                    text: `*Insights:*\n${analysis.insights.map(i => //adds bullets to the insights
                        `• ${i}`).join('\n')}`
                }
            })
        }

        if (analysis.recommendations.length > 0) {
            blocks.push({
                type: 'section',
                text: {
                    type: 'mrkdwn',
                    text: `*Recommendation:*\n${analysis.recommendations.map(i =>
                        `• ${i}`).join('\n')}`
                }
            })
        }
        blocks.push({
            type: 'context',
            elements: [
                {
                    type: 'mrkdwn',
                    text: `📊 Analyzed: ${new Date().toISOString()}`
                }
            ]
        });

        //this function actually calls slack api and post the report to channel in slack
        await this.webClient.chat.postMessage({  //we use await to things which take time,Pause here until the task finishes
            channel: process.env.SLACK_PRIVATE_CHANNEL_ID,
            text: `New Member Analysis: ${member.name} (${analysis.fitScore}/100)`, //one-line summary of the detailed report.
            attachments: [
                {
                    color: color, //Uses the color chosen earlier
                    blocks: blocks //Header + Details + Insights + Recommendations + Date
                }
            ]
        });
        log.info(`Analysis posted to channel for ${member.name}`)
    }

    //this function checks if the email is perosnal
    isPersonalEmail(email) {
        const personalDomains = ['gmail.com', 'yahoo.com', 'hotmail.com', 'outlook.com', 'icloud.com'];
        const domain = email.split('@')[1]?.toLowerCase(); //splits email from @ and gets [1] means the provider,arya@gmail.com gives gmail.com
        return personalDomains.includes(domain);
    }

    //now a function to start all the services -database,express server and thr slackbot
    async start() {
        try {
            log.info('Initilazing database...')
            await initDatabase() //Connect to database.Create tables/collections if needed.wait until databases are ready

            const port = process.env.PORT || 3000; //choose port from env if present otherwise use port 3000

            this.server = this.app.listen(port, () => {
                log.info(`🚀 Express server running on port ${port}`);
            })

            //starts slack bot
            await this.slack.start();//connect the bot to slack to start listening to slack events,
            // events like team_join,message and reactions can be received
            log.info('⚡️ Slack bot connected');
            log.info('🎉 Slack AI Agent is running!')

            if (process.env.NODE_ENV === 'development') {//Check if you're running locally,so developers know where to test.
                log.info(`Test endpoint: POST http://localhost:${port}/test/analyze-member`)
            }

        }
        catch (error) {
            log.error('failed to start: ', error.message)
            process.exit(1)
        }
    }

    //function to stop the agent,called when the applipcation is closing
    async stop() {
        log.info('Shutting down...')
        try {
            await this.slack.stop() //Stop listening for Slack events Disconnect bot
            if (this.server) { //checks if server is running if yes then
                await new Promise(resolve => this.server.close(resolve));//Stop accepting new requests Wait until server closes
            }
            await closeDatabase(); //disconnect from database
            log.info('Stopped successfully')
        } catch (error) {
            log.error('Shutdown error:', error.message)
        }
        process.exit(0)
    }
}

//ceating agent object
const agent = new SlackAIAgent()

process.on('SIGINT', () => agent.stop());
process.on('SIGTERM', () => agent.stop());

agent.start().catch(error => {
    console.error('Startup failed:', error.message);
    process.exit(1)
})

export default agent



